/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/Action.vue')['default']
    Audio: typeof import('./src/components/Audio.vue')['default']
    BuyIn: typeof import('./src/components/BuyIn.vue')['default']
    CardList: typeof import('./src/components/CardList.vue')['default']
    CardStyle: typeof import('./src/components/CardStyle.vue')['default']
    CommonCard: typeof import('./src/components/CommonCard.vue')['default']
    copy: typeof import('./src/components/Player copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    GameRecord: typeof import('./src/components/GameRecord.vue')['default']
    MsgList: typeof import('./src/components/MsgList.vue')['default']
    Notice: typeof import('./src/components/Notice.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    'Player copy': typeof import('./src/components/Player copy.vue')['default']
    Range: typeof import('./src/components/Range.vue')['default']
    Record: typeof import('./src/components/Record.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendMsg: typeof import('./src/components/SendMsg.vue')['default']
    SitList: typeof import('./src/components/SitList.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    XInput: typeof import('./src/components/XInput.vue')['default']
  }
}
